FROM aursu/rpmbuild:7-build

USER root
RUN yum -y install \
        gettext \
        glib2-devel \
        pkgconfig \
        popt-devel \
    && yum clean all && rm -rf /var/cache/yum

RUN yum -y --enablerepo=bintray-custom install \
        systemd \
    && yum clean all && rm -rf /var/cache/yum
